// Supported LLM providers
export type LLMProvider = 'openai' | 'anthropic' | 'gemini' | 'deepseek';

// Configuration for LLM request
export interface LLMConfig {
  provider: LLMProvider;
  temperature?: number;
  maxTokens?: number;
}

// Single idea generated by AI
export interface GeneratedIdea {
  title: string;
  description: string;
  rationale: string;
}

// Request body for idea generation
export interface GenerateIdeasRequest {
  persona: string;
  industry: string;
  provider?: LLMProvider;
  temperature?: number;
}

// Response structure
export interface GenerateIdeasResponse {
  success: boolean;
  ideas?: GeneratedIdea[];
  error?: string;
}

// Database idea record
export interface IdeaRecord extends GeneratedIdea {
  id: number;
  persona: string;
  industry: string;
  created_at: Date;
}
